version: "3.4"

services: 
 elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.0
    deploy:
      replicas: 5
      update_config:
        parallelism: 1
        delay: 5s
    environment:
      - "cluster.name=es-cluster"
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - "discovery.zen.minimum_master_nodes=3"
      - "network.publish_host=_eth0_"
      - "discovery.zen.ping.unicast.hosts=tasks.elasticsearch"
    networks:
      - elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
     - data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.2
    ports:
      - 5601:5601
    networks:
      - elasticsearch
    depends_on:
      - elasticsearch
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  elasticsearch:
    driver: overlay

volumes:
  data: