version: "3.4"
services: 
 elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.0
    deploy:
      replicas: 5
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        delay: 10m
    environment:
      - "network.host=_eth0_"
      - "network.publish_host=_eth0_"
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - "discovery.zen.minimum_master_nodes=3"
    networks:
      - elasticsearch
    ports:
      - 9200:9200
networks:
  elasticsearch:
    driver: overlay